name: ASConnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http_parser: ^4.0.2
  geocoding: ^4.0.0
  flutter_local_notifications: ^17.2.2
  flutter_app_badger: ^1.5.0
  flutter_localized_locales: ^2.0.5

  # Carte et géo
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  flutter_map_tile_caching: ^10.1.1   # ❗️montre la version 10.x pour latlong2 ^0.9.x
  cached_network_image: ^3.3.1

  # Divers
  http: ^1.5.0
  url_launcher: ^6.3.0
  geolocator: ^14.0.2
  geolocator_web: ^4.0.0
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: assets/icons/ASConnect.png
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/ASConnect.png
  web:
    generate: true
    image_path: assets/icons/ASConnect.png
    background_color: "#FFFFFF"
    theme_color: "#0F172A"
  windows:
    generate: true
    image_path: assets/icons/ASConnect.png
    icon_size: 48
  macos:
    generate: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/ImageFond.png
    - assets/images/FAST-France-Logo_Black.png
  # assets:
  #   - assets/icons/ASConnect.png
